--- # Playbook for template
- hosts: localhost
  gather_facts: no
  become: yes
  vars:
    code_name: whisky
    version: 4.2
  tasks:
    - name: deploy config file
      template:
        src: config.j2
        dest: /opt/config
   
